### ISSUE TITLE
Have a documentation page with all the CLI commands

### ISSUE THREAD

**Issue by cudeso** [MISP/misp-book#195]
**Describe the solution you'd like**
Documentation that lists the different CLI commands that can be issued via cake.
(can work on this myself; putting this as a reminder)

cake
cake CakeResque.CakeResque

**Describe alternatives you've considered**
Trial and error.

**Comment by pettai** [comment]
👍

**Comment by pettai** [comment]
it still seems the MISP book is empty wrt. available CLI commands, but it would be nice to have those documented.
(I've just found bits & pieces in other MISP-issues for resetting admin password etc. and looked the code as @iglocska suggested.)

**Comment by iglocska** [comment]
They are indeed missing from misp-book still, but since then we have them all documented in MISP directly. Go to event actions -> automation -> bottom of the page:

![image](https://user-images.githubusercontent.com/3668672/94276664-d422cc80-ff48-11ea-8b3e-e7798326b1c4.png)

**Comment by PROTechThor** [comment]
@cudeso Would you still like to work on this?

> They are indeed missing from misp-book still, but since then we have them all documented in MISP directly. Go to event actions -> automation -> bottom of the page:

Since we already have them in MISP, copying the same information to MISP-book should fix this issue?

**Comment by Wachizungu** [comment]
Some notes / things to potentially still change:

I only included commands I consider to be used for administrative tasks. There are others like statistics contributors that don't belong in that bucket. It might be considered better to have a dedicated CLI commands page (containing all the ones considered relevant) and then perhaps link back towards that from the administration page.

There are some conflicting / duplicate commands, for example, it is not clear to me which one below is recommended or the best:
cake Authkey [email] [api_key | optional]
cake Admin change_authkey [email] [authkey]

The text "Certain administrative tasks are exposed to the API, these help with maintaining and configuring MISP in an automated way / via external tools." under /events/automation "Administering MISP via the CLI" of MISP core is confusing to me, especially since in other parts a clear distinction is made between the REST API and the CLI.

Some functions are missing under /events/automation in MISP core (I can create a PR to fix that later together with the above message):

- restart all workers
- reset authkey

There are more functions that I don't know the actual use cases for. If I add them someone like iglocska would have to review and delete those parts that don't make sense to document here + perhaps add a short extra description.
